### ISSUE TITLE
i can't pip install oauth2lib

### ISSUE THREAD

**Issue by clark0x** [DeprecatedCode/oauth2lib#1]
can be found on pypi, but can't be installed.

$ pip install oauth2lib
Downloading/unpacking oauth2lib
  Could not find any downloads that satisfy the requirement oauth2lib
Cleaning up...
No distributions at all found for oauth2lib
Storing complete log in /Users/clark/.pip/pip.log

**Comment by ghost** [comment]
I'd like to confirm that problem exists.

```
/home/tsokolowski/.virtualenvs/sqd-api/bin/pip run on Sun Nov 17 16:36:41 2013
Downloading/unpacking oauth2lib

  Getting page https://pypi.python.org/simple/oauth2lib/
  URLs to search for versions for oauth2lib:
  * https://pypi.python.org/simple/oauth2lib/
  Analyzing links from page https://pypi.python.org/simple/oauth2lib/
  Could not find any downloads that satisfy the requirement oauth2lib

No distributions at all found for oauth2lib

Exception information:
Traceback (most recent call last):
  File "/home/tsokolowski/.virtualenvs/sqd-api/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/home/tsokolowski/.virtualenvs/sqd-api/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/tsokolowski/.virtualenvs/sqd-api/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1026, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/tsokolowski/.virtualenvs/sqd-api/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/index.py", line 171, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for oauth2lib
```

**Comment by hnk** [comment]
The package metadata seems to be in PyPI, but no source has been added yet...

**Comment by ghost** [comment]
The thing is the package was "installable" via pypi few days before the issue was reported.

**Comment by ruipacheco** [comment]
Still happening today. Any plans to fix this?

**Comment by thomasbiddle** [comment]
Still an issue.

**Comment by NateFerrero** [comment]
Hey guys - I will fix this shortly. It was never formally released, I'm working on a bit more documentation and cleanup and hope to release it soon.

**Comment by KarishmaGhiya** [comment]
Hey! Is this issue fixed?

**Comment by ochawkeye** [comment]
FYI, you can pip install directly from github.

`pip install git+https://github.com/NateFerrero/oauth2lib.git`
